# Generated by Django 2.1.7 on 2019-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('xp_comp', models.IntegerField(default=0)),
                ('min_silver_comp', models.IntegerField(default=0)),
                ('max_silver_comp', models.IntegerField(default=0)),
                ('cd_comp', models.IntegerField(default=0)),
            ],
        ),
    ]
