# Generated by Django 2.1.7 on 2019-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0002_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
