# Generated by Django 2.1.7 on 2019-02-28 13:36

from django.db import migrations, models

from oxemHeroes.classe.models import Classe


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Classe.objects.create(name="lord_typus", xp_comp=10, min_silver_comp=10, max_silver_comp=40, cd_comp=30, price=2500)


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0003_classe_price')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
