# Generated by Django 2.1.7 on 2019-03-19 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('bonus', models.IntegerField(default=0, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.Command')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commandhistory',
            unique_together={('member', 'command')},
        ),
    ]
