# Generated by Django 2.1.7 on 2019-03-18 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0002_classes'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMember',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.Member')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('experience', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('token', models.IntegerField(default=0)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.Classe')),
            ],
        ),
    ]
