# Generated by Django 2.1.7 on 2019-03-21 15:11

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('gameMember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemember',
            name='max_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemember',
            name='inventory',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'hero': []}),
        ),
    ]
