# Generated by Django 2.1.7 on 2019-02-28 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..models import Command


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Command.objects.create(name="choisir",
                           description="Permet de chosir un héros parmis ceux disponibles.",
                           how_to="!choisir <heros> (retirer les <> et indiquer le nom du héros de votre choix.")

    Command.objects.create(name="xp",
                           description="Affiche votre niveau, le titre attribué à ce niveau ainsi que l'xp total gagné.",
                           how_to="!xp")

    Command.objects.create(name="silver",
                           description="Permet d'afficher la quantité de silver possédée.",
                           how_to="!silver")

    Command.objects.create(name="silvermax",
                           description="Permet d'afficher la quantité de silver récoltée depuis le début du serveur.",
                           how_to="!silvermax")

    Command.objects.create(name="jeton",
                           description="Permet d'afficher votre quantité de jetons possédée.",
                           how_to="!jeton")

    Command.objects.create(name="bonusxp",
                           description="Permet de modifier le bonus d'xp.",
                           how_to="!bonusxp <25> (retirer les <> et 25 pour 25%.)")

    Command.objects.create(name="addsilver",
                           description="Permet d'attribuer des silvers à un joueur.",
                           how_to="!addsilver <25> <@joueur> (retirer les <> et indiquer le joueur avec son @).")

    Command.objects.create(name="addjeton",
                           description="Permet d'attribuer des jetons à un joueur.",
                           how_to="!addjeton <25> <@joueur> (retirer les <> et indiquer le joueur avec son @).")

    Command.objects.create(name="aquillon",
                           description="Permet d'utiliser Aquillon de Shosizuke.",
                           how_to="!aquillon")

    Command.objects.create(name="justice",
                           description="Permet d'utiliser Justice de Oxem.",
                           how_to="!justice")

    Command.objects.create(name="pillage",
                           description="Permet d'utiliser Pillage de Talkoran.",
                           how_to="!pillage")

    Command.objects.create(name="giveaway",
                           description="Démarre un giveaway.",
                           how_to="!giveaway")

    Command.objects.create(name="participer",
                           description="Participer à un giveaway.",
                           how_to="!participer")

    Command.objects.create(name="gagnant",
                           description="Designe un/des gagnant(s) au giveAway.",
                           how_to="!gagnant <2> (retirer les <> et indiquer un nombre de gagnant, ce paramètre est optionnel)")


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
