# Generated by Django 2.1.7 on 2019-02-28 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..models import Command


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Command.objects.create(name="recruter",
                           description="Permet de recruter un héros payant parmis ceux disponibles.",
                           how_to="!recruter <heros> (retirer les <> et indiquer le nom du héros de votre choix.")

    Command.objects.create(name="potion",
                           description="Permet d'utiliser potion de Lord Typus.",
                           how_to="!potion")


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_commands')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
