# Generated by Django 2.1.7 on 2019-02-27 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('experience', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField()),
                ('discriminator', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Member'),
        ),
    ]
