# Generated by Django 2.1.7 on 2019-02-28 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..models import Command


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Command.objects.create(name="choisir",
                           description="Permet de chosir un héros parmis ceux disponibles.",
                           how_to="!choisir <heros> (retirer les <> et indiquer le nom du héros de votre choix.")

    Command.objects.create(name="xp",
                           description="Affiche votre niveau, le titre attribué à ce niveau ainsi que l'xp total gagné.",
                           how_to="!xp")

    Command.objects.create(name="silver",
                           description="Permet d'afficher la quantité de silver générée par les membres de la commu.",
                           how_to="!choisir <heros> (retirer les <> et indiquer le nom du héros de votre choix.")

    Command.objects.create(name="contribution",
                           description="Permet d'afficher votre contribution aux silver totaux.",
                           how_to="!contribution")

    Command.objects.create(name="bonusxp",
                           description="Permet de modifier le bonus d'xp.",
                           how_to="!bonusxp <25> (retirer les <> et 25 pour 25%.)",
                           admin_command=True)

    Command.objects.create(name="addsilver",
                           description="Permet d'attribuer des silvers à un joueur.",
                           how_to="!addsilver <@joueur> (retirer les <> et indiquer le joueur avec son @).",
                           admin_command=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
