# Generated by Django 2.1.7 on 2019-02-28 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..models import Classe


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Classe.objects.create(name="oxem")
    Classe.objects.create(name="talkoran")
    Classe.objects.create(name="shosizuke")


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_commands')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
