# Generated by Django 2.1.7 on 2019-02-28 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from ..models import Game


def add_commands(apps, schema_editor):
    """Mise en places des commandes dans la BDD."""

    Game.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_classes')
    ]

    operations = [
        migrations.RunPython(add_commands)
    ]
